# baseURL: ""
languageCode: "en-us"
title: "OpenSec"
theme: "anubis"

menu:
  main:
  - identifier: archive
    name: Newsletter Archive
    title: Newsletter Archive
    url: /posts/
    weight: 0

params:
  author: "Progressive Coders Network"
  # email: mail@example.org # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false
  disableSummary: false
  # utteranc.es support
  # utterancesRepo: ""  # mandatory
  # utterancesTheme: "" # optional
  # utterancesIssue: "" # optional
  # utterancesLabel: "" # optional
  # webmentions:
  #   url: https://yourdomain.com/webemntions/receive
  #   login: hugo-theme-anubis
  #   pingback: true
  social:
  - id: github
    name: ProgressiveCoders
    # url: "https://github.com/ProgressiveCoders/OpenSec"
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

# markup:
#   goldmark:
#     renderer:
#       unsafe: true # enable raw HTML in Markdown